name: Supa-Backup
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: staging
  #pull_request:
  # branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Supa-Backup
        uses: mansueli/supa-backup@v0.0.6
        with:
          supabase_url: http://206.189.160.210:3002/project/default
         # supabase_password: SUPABASE_PASSWORD
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Supabase backup
