name: Continuous Integration / Deployment
on:
  push:
    branches: release

jobs:
  dockerhub:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      name: Login to Harbor
        run: docker login hub.emeraldigital.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_TOKEN }}
      - uses: actions/checkout@master
      - name: build and push to docker
      - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
