name: Database Backup
on:
  push:
    branches: release #Validar rama donde se hara el push.

jobs:
  avoid_redundancy:
    name: Kill previous runs
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous started workflows
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  linter_build:
    needs: [avoid_redundancy]
    name: Run linter and build
    runs-on: ubuntu-20.04
    steps:
      - name: Pull from repo
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Set up node version
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        
  test:
    needs: [linter_build]
    runs-on: ubuntu-20.04
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node version
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  e2e:
    needs: [linter_build]
    runs-on: ubuntu-20.04
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node version
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000
          
  backup_database: #Validar en que servidor se va a generar el respaldo.
    needs: [test, e2e]
    name: Database backup
    runs-on: ubuntu-20.04
    steps:
      - name: Backup bd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EMERALD_HOST }}
          username: ${{ secrets.EMERALD_USER }}
          password: ${{ secrets.EMERALD_PASSWORD }}
          port: 22   #Validar puerto
          script: |
            cd bara-monitoreo/bara-web-client/  #Validar directorio en donde estara el backup.sh
            git add . && git stash
            git pull origin development
            chmod 777 ./backup.sh
            ./backup.sh
        #Valida si se agregaran también jobs de deploy o si se manejaran por separado.  
          
