name: Database Backup
on:
  push:
    branches: staging #Validar rama donde se hara el push.
jobs:
          
   backup:
     #needs: [test, e2e]
     runs-on: ubuntu-20.04
     steps: 
      - name: Backup Databases
        uses: actions/checkout@v2
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v2.3
        with:
          database_url: postgres://postgres:postgres@localhost:5431/postgres
          #postgres://postgres:${{secrets.POSTGRES_PWD}}@206.189.160.210:5431/postgres
          path: "backups/backup_postgres.sql" 
          options: "-O" 
          
      - name: Transfer backup to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.EMERALD_HOST}}
          username: ${{secrets.EMERALD_USER}}
        #  key: ${{ secrets.SSH_PRIVATE_KEY}}
          source: /tmp/backup.sql
          target: /path/to/backup/backup.sql
        
          
          
