name: Database Backup
on:
  push:
    branches: staging #Validar rama donde se hara el push.
jobs:
          
   backup:
     #needs: [test, e2e]
     runs-on: ubuntu-20.04
     steps: 
      - name: Backup Databases
        run: |
           docker exec -t supabase-db  pg_dump -U postgres  -d postgres -h localhost  -p 5432 -F p > backup_postgres.sql
          #sudo docker exec -t supabase-db  pg_dump -U postgres  -d postgres -h 206.189.160.210  -p 5431 -F p > backup_postgres.sql

     #   pg_dump -U ${{ secrets.EMERALD_USER}} -h 206.189.160.210 -d postgres > backup.sql
     #    uses: actions/checkout@v2
     # - name: Postgres Dump Backup
     #   uses: tj-actions/pg-dump@v2.3
     #   with:

     #     database_url: postresql://postgres:${{secrets.POSTGRES_PWD}}@206.189.160.210:5431/postgres
          #postgres://postgres:postgres@localhost:5431/db
          #postgres://postgres:${{secrets.POSTGRES_PWD}}@localhost:5431/db
          #postgres://postgres:${{secrets.POSTGRES_PWD}}@206.189.160.210:5431/postgres
     #     path: "backups/backup_postgres.sql" 
     #     options: "-O" 
      
     # - name: Transfer backup to remote server
     #   uses: appleboy/scp-action@master
     #   with:
     #     host: ${{secrets.EMERALD_HOST}}
     #     username: ${{secrets.EMERALD_USER}}
     #     key: ${{ secrets.SSH_PRIVATE_KEY}}
     #     source: /tmp/backup.sql
     #     target: /path/to/backup/backup.sql
          
      
        
          
          
