name: Continuous Integration

on:
  push:
    branches: [release]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: execute bash script for deploy backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd app
            git pull origin release
            docker build -t react-app .
            docker run --name react-app -p 8080:80 react-app .


