name: Continuous Integration

on: 
  push:
    branches: [staging]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel previous started workflows 
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node version
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node version
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build project 
        run: npm run build
      - name: Copy build directory
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node version
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  e2e:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    steps:
      - name: Pull from repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up node version
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: E2E tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start
          wait-on: http://localhost:3000
  
  publish:
    needs: [test, e2e]
    runs-on: ubuntu-18.04
    name: Build and push into release
    steps:
      - name: Pull repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy build directory
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Copy README.md to dist directory
        run: cp README.md dist/
      - name: Publish into release branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release # The branch name where you want to push the assets
          FOLDER: dist # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Automated build: [{sha} {msg}]" # The commit message
