name: Playwright Tests Containeired
on:
  push:
    branches: [ release ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test login_first.spec.js --project chromium
      - name: Run login
        run: npx playwright test login.spec.js --project chromium
        - name: Run Jugador
        run: npx playwright test Jugador.spec.js --project chromium
        - name: Run organizador
        run: npx playwright test auth_organizador.spec.js --project chromium
             # npx playwright test deletes_organizador.spec.js &&
             # npx playwright test deletes_jugador.spec.js
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          EMAIL_ORGANIZADOR: ${{secrets.EMAIL_ORGANIZADOR}}
          EMAIL_JUGADOR: ${{secrets.EMAIL_JUGADOR}}
          LOGIN_PWD: ${{secrets.LOGIN_PWD}}